### ISSUE TITLE
Ilia file window is showing empty results and segfault on "enter" key

### ISSUE THREAD

**Issue by klew** [regolith-linux/ilia#23] opened 2022-06-02 07:34 UTC
First problem: file finder in ilia luncher isn't working. I have empty list of files regardless what I type in input.  

Second: ilia file window is causing segfault when I type something in search field and press enter. Here is output of syslog:

    Jun  1 09:29:50 io ilia[1898795]: Failed to load module "xapp-gtk3-module"
    Jun  1 09:29:50 io ilia[1898795]: message repeated 2 times: [ Failed to load module "xapp-gtk3-module"]
    Jun  1 09:30:01 io kernel: [420083.186617] ilia[1898795]: segfault at 30 ip 00007ff52ee89c82 sp 00007fffacb1bb20 error 4 in libgtk-3.so.0.2404.29[7ff52ebad000+383000]
    Jun  1 09:30:01 io kernel: [420083.186626] Code: 00 00 49 89 e6 48 89 ee 44 89 fa 48 89 df 4c 89 f1 e8 e2 e7 ff ff 48 8b 3c 24 e8 59 33 d3 ff 66 0f ef c0 31 f6 4c 8d 4c 24 20 <48> 8b 48 30 49 89 c0 0f 29 44 24 20 0f 29 44 24 30 0f 29 44 24 40
    Jun  1 09:30:01 io ilia[1898795]: gtk_tree_model_filter_get_value: assertion 'GTK_TREE_MODEL_FILTER (model)->priv->stamp == iter->stamp' failed
    Jun  1 09:30:01 io ilia[1898795]: ../../../gobject/gtype.c:4333: type id '0' is invalid
    Jun  1 09:30:01 io ilia[1898795]: can't peek value table for type '<invalid>' which is not currently referenced
    Jun  1 09:30:03 io regolith.desktop[1898434]: Failed to aquire access to input devices, aborting.
    Jun  1 09:30:03 io regolith.desktop[1898794]: Segmentation fault (core dumped)

Ilia version: 0.12.2-jammy-1regolith
OS: Ubuntu 22.04 LTS (5.15.0-33-generic)

**Comment by klew** [comment] 2022-06-03 07:11
The same crash happens on "windows" tab in ilia when some none existing string is typed and then press enter.

**Comment by kgilmer** [comment] 2022-07-06 15:03
The window crash was addressed I believe, although I'm having trouble finding the commit now.  The fix should be available in Regolith 2.1 Beta 2 or currently in the `unstable` repo.

The file search issue may have been addressed in the above commits.  The text entry was being used in the tracker full text search (intended) *and* filtering the result text (unintended).  The net result being that only files containing the search string in the file path would be shown.  

It's hard to say if that fixes all issues here.  If tracker issues persist please provide more details so that the problem can be reproduced.  Meaning provide a sample file, specify where it is located on your system, and the behavior you see and what you expect.

**Comment by carderne** [comment] 2022-07-07 09:13
Switched to the unstable repo, and the empty/segfault is gone.

For me it still (a) has too much lag and (b) presents search results in a strange order.
Happy to take those to Slack (or open separate issues if that would be useful.)

**Comment by klew** [comment] 2022-07-21 08:03
On 2.1 segfault is gone. List is populated with files. It's ok for me to close this issue

**Comment by kgilmer** [comment] 2022-07-22 15:01
@carderne can you provide more detail about the lag?  Is it start up time, time to see results after entrying a search term, time when scrolling between items in the list, time from selecting and item to seeing an app launch?

Regarding the sort order (or lack of, due to no `ORDER BY` clause), it's determined by this query expression: https://github.com/regolith-linux/ilia/blob/main/src/tracker/TrackerPage.vala#L141.  If you find another query that gives results in a more intuitive order LMK and we can update the query.  Here is a page w/ examples on how to execute queries from the command line: https://wiki.gnome.org/Projects/Tracker/Documentation/Examples/SPARQL/FTS

Will close this issue as the main issue is resolved, please open specific issues as needed.

**Closed by kgilmer** 2022-07-22 15:01 UTC
